source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/china_ios/cocoapods-specs.git'

#--sources=https://gitee.com/china_ios/cocoapods-specs.git,https://github.com/CocoaPods/Specs.git

platform :ios, '13.0'

target 'GXSwiftNetwork_Example' do
  
  use_frameworks!
  
  pod 'GXSwiftNetwork', :path => '../'
  pod 'GGXSwiftExtension'
  
# 本地
#  pod 'PKHUD', :path => '~/Desktop/SourceTree/PKHUD'
# 远程，只要上面Source源包含此组件，默认优先查找，不添加`git`路径
#  pod 'PKHUD', :git => "https://gitee.com/china_ios/PKHUD.git"

  #  pod 'PKHUD', '6.0.0'
end

# 解决`libarclite`库Xcode14.3丢失问题
post_install do | installer |
  installer.pods_project.targets.each do | target |
    target.build_configurations.each do | config |
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
