use_frameworks!

platform :ios, '11.0'

target 'GXSwiftNetwork_Example' do
  pod 'GXSwiftNetwork', :path => '../'

  target 'GXSwiftNetwork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
