source 'https://gitee.com/gtools/mxs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

target 'GXSwiftNetwork_Example' do
  
  use_frameworks!
  
  pod 'GXSwiftNetwork', :path => '../'
  pod 'GGXSwiftExtension'
  
end

# 解决`libarclite`库Xcode14.3丢失问题
post_install do | installer |
  installer.pods_project.targets.each do | target |
    target.build_configurations.each do | config |
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
